# import pytest
# from webscrapper import *

# def test_year_to_text_1999():
#     webscrapper = WebScrapper('1999')
#     year_to_text_test = ['While the FOMC did not take action today to alter the stance of monetary policy, the Committee was concerned about the potential for a buildup of inflationary imbalances that could undermine the favorable performance of the economy and therefore adopted a directive that is tilted toward the possibility of a firming in the stance of monetary policy. Trend increases in costs and core prices have generally remained quite subdued. But domestic financial markets have recovered and foreign economic prospects have improved since the easing of monetary policy last fall. Against the background of already-tight domestic labor markets and ongoing strength in demand in excess of productivity gains, the Committee recognizes the need to be alert to developments over coming months that might indicate that financial conditions may no longer be consistent with containing inflation.', 'Owing to the uncertain resolution of the balance of conflicting forces in the economy going forward, the FOMC has chosen to adopt a directive that includes no predilection about near-term policy action. The Committee, nonetheless, recognizes that in the current dynamic environment it must be especially alert to the emergence, or potential emergence, of inflationary forces that could undermine economic growth.', 'In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of Boston, New York, Philadelphia, Cleveland, Richmond, Atlanta, Chicago, St. Louis, Kansas City, and San Francisco. The discount rate is the interest rate that is charged depository institutions when they borrow from their district Federal Reserve Banks.', 'Against this background, the Committee adopted a directive that was biased toward a possible firming of policy going forward. Committee members emphasized that such a directive did not signify a commitment to near-term action. The Committee will need to evaluate additional information on the balance of aggregate supply and demand and conditions in financial markets.', 'In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of Boston, Cleveland, Richmond and Kansas City. The discount rate is the rate charged depository institutions when they borrow short-term adjustment credit from their district Federal Reserve Banks.', 'Nonetheless, in light of market uncertainties associated with the century date change, the Committee decided to adopt a symmetric directive in order to indicate that the focus of policy in the intermeeting period must be ensuring a smooth transition into the Year 2000. At its next meeting the Committee will assess available information on the likely balance of supply and demand, conditions in financial markets, and the possible need for adjustment in the stance of policy to contain inflationary pressures.']
#     assert webscrapper.year_to_text['1999'] == year_to_text_test

# def test_year_to_text_2000():
#     webscrapper = WebScrapper('2000')
#     year_to_text_test = ['In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of Boston, New York, Philadelphia, Cleveland, Richmond, Atlanta, Chicago, St. Louis, Kansas City and San Francisco. The discount rate is the rate charged depository institutions when they borrow short-term adjustment credit from their district Federal Reserve Banks.', 'In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of Boston, New York, Philadelphia, Cleveland, Richmond, Atlanta, Chicago, St. Louis, Minneapolis, Kansas City and San Francisco. The discount rate is the rate charged depository institutions when they borrow short-term adjustment credit from their district Federal Reserve Banks.', 'In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of Boston, Cleveland, Richmond, and San Francisco. The discount rate is the rate charged depository institutions when they borrow short-term adjustment credit from their district Federal Reserve Banks.', 'In these circumstances, and against the background of its long-term goals of price stability and sustainable economic growth and of the information currently available, the Committee believes the risks continue to be weighted mainly toward conditions that may generate heightened inflation pressures in the foreseeable future.', 'Against the background of its long-term goals of price stability and sustainable economic growth and of the information currently available, the Committee believes the risks continue to be weighted mainly toward conditions that may generate heightened inflation pressures in the foreseeable future.', 'Against the background of its long-term goals of price stability and sustainable economic growth and of the information currently available, the Committee believes the risks continue to be weighted mainly toward conditions that may generate heightened inflation pressures in the future.', 'Nonetheless, to date the easing of demand pressures has not been sufficient to warrant a change in the Committee\'s judgment that against the background of its long-run goals of price stability and sustainable economic growth and of the information currently available, the risks continue to be weighted mainly toward conditions that may generate heightened inflation pressures in the foreseeable future.', 'Against the background of its long-run goals of price stability and sustainable economic growth and of the information currently available, the Committee consequently believes that the risks are weighted mainly toward conditions that may generate economic weakness in the foreseeable future.']
#     assert webscrapper.year_to_text['2000'] == year_to_text_test

# def test_year_to_text_2001():
#     webscrapper = WebScrapper('2001')
#     year_to_text_test = ['In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of New York, Philadelphia, Cleveland, Atlanta, Chicago, St. Louis, Minneapolis, Dallas and San Francisco.', 'In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of all twelve Reserve Banks.', 'In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of New York, Richmond, Chicago, St. Louis and San Francisco.', 'In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of Boston, New York, Philadelphia, Atlanta, Chicago, Dallas and San Francisco.', 'In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of Boston, New York, Philadelphia, Richmond, Chicago, Kansas City and Dallas.', 'In taking the discount rate action, the Federal Reserve Board approved requests submitted by the Boards of Directors of the Federal Reserve Banks of Boston, New York, Cleveland, Richmond, Atlanta, St. Louis, Kansas City and San Francisco.', 'In taking the discount rate action, the Federal Reserve Board approved the request submitted by the Board of Directors of the Federal Reserve Bank of Richmond.', 'In taking the discount rate action, the Federal Reserve Board approved the requests submitted by the Boards of Directors of the Federal Reserve Banks of Boston, New York, Philadelphia, Chicago and San Francisco.']
#     assert webscrapper.year_to_text['2001'] == year_to_text_test
